// Auto generated by utensor-cli

#include <stdint.h>

const int inline_MatMul_eightbit_Placeholder__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_MatMul_eightbit_Placeholder__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const float inline_Variable_0 [ 20 ] = {  1.2979158,  -0.10008734,  -2.458088,  0.04307403,  2.4584837,  0.057300486,  0.015427831,  -0.11499055,  0.029739562,  -1.1878587,  1.2978791,  -0.040049396,  2.4580836,  0.013938822,  -2.4586282,  0.14373153,  -0.045620494,  0.024762116,  -0.046494137,  -1.1878308,  };
#include <stdint.h>

const int inline_MatMul_eightbit_Variable__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_MatMul_eightbit_Variable__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const float inline_Variable_1_0 [ 10 ] = {  -1.2978952,  0.60823494,  -6.496146e-05,  -0.10388129,  -0.00012764256,  -1.19964625e-08,  0.5450806,  -0.026890675,  -0.08001271,  1.1879171,  };
#include <stdint.h>

const int inline_add_eightbit_Variable_1__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_add_eightbit_Variable_1__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const float inline_Variable_2_0 [ 20 ] = {  1.5890677,  -1.5712352,  0.32697612,  -0.52235126,  -2.4336922,  2.4675722,  -0.04376048,  -0.055695057,  -2.4098685,  2.4934258,  -0.23014432,  -0.106933765,  0.40485802,  -0.3563779,  0.06948651,  0.0595569,  -0.035241153,  -0.030667994,  1.5052203,  -1.3964539,  };
#include <stdint.h>

const int inline_MatMul_1_eightbit_Variable_2__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_MatMul_1_eightbit_Variable_2__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const float inline_Variable_3_0 [ 2 ] = {  1.5728669,  -1.460082,  };
#include <stdint.h>

const int inline_add_1_eightbit_Variable_3__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_add_1_eightbit_Variable_3__port__0_reduction_dims_0 [ 1 ] = {  0,  };
