// Auto generated by utensor-cli

#include <stdint.h>

const int inline_MatMul_eightbit_Placeholder__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_MatMul_eightbit_Placeholder__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const float inline_Variable_0 [ 20 ] = {  -1.779113,  0.014425228,  2.1459432,  -0.079968356,  -1.268849,  0.4233583,  -0.16075294,  -1.9612513,  1.0842161,  0.81448466,  -1.7790484,  0.038112532,  2.494147,  0.023867516,  -1.268851,  -0.1663366,  -0.15246516,  1.9612117,  -0.45581585,  -0.2594202,  };
#include <stdint.h>

const int inline_MatMul_eightbit_Variable__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_MatMul_eightbit_Variable__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const float inline_Variable_1_0 [ 10 ] = {  1.7791137,  -0.17571531,  -2.1460483,  -0.13133042,  1.2688822,  0.21178003,  0.1607369,  5.694488e-06,  0.6379674,  0.6444721,  };
#include <stdint.h>

const int inline_add_eightbit_Variable_1__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_add_eightbit_Variable_1__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const float inline_Variable_2_0 [ 20 ] = {  2.134509,  -2.2068267,  -0.10720505,  -0.08867391,  2.6205146,  -2.905687,  -0.015934236,  -0.013375406,  1.5346963,  -1.5617563,  -0.4028301,  0.3047896,  0.08289706,  -0.22134615,  -1.9139987,  1.989451,  -0.9781099,  0.90772635,  -0.78939855,  0.70346653,  };
#include <stdint.h>

const int inline_MatMul_1_eightbit_Variable_2__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_MatMul_1_eightbit_Variable_2__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const float inline_Variable_3_0 [ 2 ] = {  -0.6859275,  0.796309,  };
#include <stdint.h>

const int inline_add_1_eightbit_Variable_3__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_add_1_eightbit_Variable_3__port__0_reduction_dims_0 [ 1 ] = {  0,  };
