// Auto generated by utensor-cli

#ifndef __MODELS_XOR_RELU_H
#define __MODELS_XOR_RELU_H
#include "uTensor/core/context.hpp"
void get_xor_relu_ctx(Context& ctx, Tensor* input_0);
#endif // __MODELS_XOR_RELU_H